### ISSUE TITLE
Task does not terminate

### ISSUE THREAD

**Issue by zenderol** [sitespeedio/grunt-sitespeedio#1]
Hi Peter,
First of all, thanks for the great work!
Unfortunately the grunt task does not terminate:

---

Running "sitespeedio:default" (sitespeedio) task
Verifying property sitespeedio.default exists in config...OK
File: [no files]
Options: resultBaseDir="/tmp", urls=["http://www.sitespeed.io","http://www.sitespeed.io/faq/"]
info: OS: 'darwin 13.1.0', Node.js: 'v0.10.26', sitespeed: '3.1.2', phantomJs: '1.9.8', java: '1.8.0_20', browsertime: '0.8.21'
info: Will analyze 2 pages
info: Running YSlow for http://www.sitespeed.io [phantomjs]
info: Running YSlow for http://www.sitespeed.io/faq/ [phantomjs]
info: Done analyzing urls
info: Wrote results to /tmp/www.sitespeed.io/2015-02-11-14-01-14 

---
## I used this configuration:

default: {
            options: {
                urls: ["http://www.sitespeed.io", "http://www.sitespeed.io/faq/"],
                resultBaseDir: "/tmp"
            }
        }

---

after the last info message, the task stays like this (I waited for 5 minutes) and also there is no html written to the result directory. Any idea why or how to trace the error?

**Comment by soulgalore** [comment]
Hi @zenderol ,
thanks for the report! first, the default behaviour was to not publish any HTML result, a miss by me. The other bug was because the done method was only called when using a budget.

I've published 0.1.2 that fixes both, hope it will work now :)

Best
Peter

**Comment by soulgalore** [comment]
I'm closing this, working now right?

**Comment by zenderol** [comment]
correct!
