### ISSUE TITLE
Using the file: parameter (equivalent to the CLI --file) doesn't get processed

### ISSUE THREAD

**Issue by stephenwil** [sitespeedio/grunt-sitespeedio#2]
Attempting to use the config option of 'file:', e.g.
options: {
  files: 'urls.txt',
  ...
}
doesn't get passed properly, and the grunt plugin fails.
"You must specify either a URL to test or an array with URL:s"

Suspect it's possibly to with the processing of the config options, in the sitespeed node module - /node_modules/lib/cli.js vs /lib/config.js

In the cli.js, L392, we set urls from file
if (cli.file) {
  cli.urls = fileHelper.getFileAsArray(cli.file);
}

No equivalent via config?

**Comment by soulgalore** [comment]
Hey @stephenwil ,
thanks for reporting the issue. When I made it I just added conf through grunt (with <code>urls</code>) but it maybe makes sense to also supply the urls via a standalone file). I'll do a fix tomorrow and ping this issue when it's out.

Best
Peter

**Comment by soulgalore** [comment]
hey Stephen,
pushed 0.1.4 with a fix. Thanks again for reporting! Please update the issue if it works for you so I can close the issue :)

Best
Peter

**Comment by stephenwil** [comment]
Brilliant - thanks; I was populating the {urls:...} as you suggest to get by, but I'll fetch the update and check it out. 
Appreciate it. 

Thanks

Stephen

**Comment by soulgalore** [comment]
closing
