### ISSUE TITLE
sitespeed run different urls with different configs

### ISSUE THREAD

**Issue by followingjoneses** [sitespeedio/grunt-sitespeedio#20]
Currently I am running sitespeed with multiple urls and a single config.

```
const budgetOptions = {
  plugins,
  browsertime: {
    pageCompleteCheck,
    preScript,
    iterations,
    browser,
    connectivity,
  },
  budget: {
    config: budgetConfig,
    output: 'junit',
  },
  outputFolder,
  urls: budgetUrl,
};

sitespeed.run(budgetOptions);
```

Where *budgetUrl* is an array with multiple urls, and *budgetConfig* represents config.

The fact here is I am testing several urls with a same config. Now I want to test each of the urls with a different config. Is that possible for just running one sitespeed process(without running multiple processes)? Thanks.

**Comment by soulgalore** [comment]
Hi @jzlshitian. No, you need to start a new one each time.

Best
Peter

**Comment by followingjoneses** [comment]
Currently I am testing different configs with travis. Once the sitespeed finishes, it will shut down the process, which means that I have to  restart it manually. Is there some method that can make this automatically? Any suggestions? @soulgalore

**Comment by soulgalore** [comment]
You can wrap the sitespeed object yourself and then just create a new for each of your config?

**Comment by followingjoneses** [comment]
Yeah I got an idea. Thanks.
