### ISSUE TITLE
The task does not terminate if Graphite or WebPageTest is not reachable

### ISSUE THREAD

**Issue by zenderol** [sitespeedio/grunt-sitespeedio#4]
With the current version (0.1.8), the task does not terminate if Graphite or WebPageTest is not reachable. For example:

```
[31merror[39m: Couldn't send data to Graphite:Error: connect ETIMEDOUT for     host:ec2-54-93-58-51.eu-central-1.compute.amazonaws.com port:2003
```

After the message above, the task hangs and does not terminate, which is very unpleasant of the task is executed on a CI.

**Comment by soulgalore** [comment]
Hi @zenderol ,
thanks for the report. Yes for Graphite I can reproduce, seems like the issue is in sitespeed.io, will look at it asap. 

For WebPageTest the task terminate, can you give me an example config that doesn't work for you so I can reproduce?

Best
Peter

**Comment by soulgalore** [comment]
I fixed the problem in sitespeed and will do a release tomorrow, want to cleanup the grunt task in the same go though.

**Comment by zenderol** [comment]
With WebPageTest it only happens if my private WebPageTest Instance can't reach a Test agent location. Do you think its possible to configure a time-out if nothing comes back from WebPageTest server?
A big thank you for the quick response!

**Comment by soulgalore** [comment]
If you add <code>verbose:true</code> and share an anonymoused log, then I can see if it happens within sitespeed or in the https://github.com/marcelduran/webpagetest-api that we use. If it is in sitespeed I can fix it, else if you could create an issue in the api that would be great!

**Comment by zenderol** [comment]
Running "sitespeedio:testOnly" (sitespeedio) task
Verifying property sitespeedio.testOnly exists in config...OK
File: [no files]
Options: resultBaseDir="target/.tmp", html, urls=["http://www.sitespeed.io","http://www.sitespeed.io/documentation"], no=2, skipTest="ycookiefree,longexpirehead,ycdn,avoidscalingimages", wptKey="ANONYM, wptHost="ANONYM", wptConfig={"location":"EU-CENTRAL_wptdriver:Chrome","timeout":800,"video":false,"firstViewOnly":false}
info: OS: 'darwin 13.1.0', Node.js: 'v0.10.26', sitespeed.io: '3.1.11', PhantomJS: '1.9.8', java: '1.8.0_20', browsertime: '0.8.26'
info: Will analyze 2 pages
info: Running YSlow for http://www.sitespeed.io [phantomjs]
info: Running YSlow for http://www.sitespeed.io/documentation [phantomjs]
info: Running WebPageTest http://www.sitespeed.io pollResults=10, timeout=800, firstViewOnly=false, runs=2, private=true, aftRenderingTime=true, location=EU-CENTRAL_wptdriver:Chrome, connectivity=Cable, video=false
info: Running WebPageTest http://www.sitespeed.io/documentation pollResults=10, timeout=800, firstViewOnly=false, runs=2, private=true, aftRenderingTime=true, location=EU-CENTRAL_wptdriver:Chrome, connectivity=Cable, video=false

_I'm going to create an issue for marcelduran!_

**Comment by soulgalore** [comment]
cool thanks!
