### ISSUE TITLE
Budget Checking step cannot access some parameters

### ISSUE THREAD

**Issue by zenderol** [sitespeedio/grunt-sitespeedio#6]
During the Budget Checking step, the parameter _includePassed_ is always 'undefined'.  For example:

---

Running "sitespeedio:testOnlyDebug" (sitespeedio) task
Verifying property sitespeedio.testOnlyDebug exists in config...OK
File: [no files]
Options: resultBaseDir="target/.tmp/sitespeed-results", html, urls=["http://sitespeed.io","http://sitespeed.io/documentation"], no=2, includePassed="true", skipTest="ycookiefree,longexpirehead,ycdn,avoidscalingimages", budget={"rules":{"default":50}}
info: OS: 'darwin 13.1.0', Node.js: 'v0.10.26', sitespeed.io: '3.1.12', PhantomJS: '1.9.8', java: '1.8.0_20', browsertime: '0.8.26'
info: Using configured web perf budget {"rules":{"default":50}}
info: Will analyze 2 pages
info: Running YSlow for http://sitespeed.io [phantomjs]
info: Running YSlow for http://sitespeed.io/documentation [phantomjs]
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file detailed-site-summary.html
info: Wrote file rules.html
info: Wrote file sitespeed.io.html
info: Wrote file index.html
info: Wrote file budget.html
info: Wrote file sitespeed.io-documentation.html
info: Wrote results to /Users/ozender/dev/git/funkotron/target/.tmp/sitespeed-results/sitespeed.io/2015-03-17-14-16-25
info: The analyze took a few seconds (7 seconds)

> > ------------------------------------------------- Check budget
> > Will not include passing tests. Change this by set grunt config to includePassed to true/false
> > Skipping ycookiefree :Use cookie-free domains http://sitespeed.io  value [100]
> > Skipping avoidscalingimages :Never scale images in HTML http://sitespeed.io  value [60]
> > Skipping longexpirehead :Have expires headers equals or longer than one year http://sitespeed.io  value [100]
> > Skipping ycdn :Use a Content Delivery Network (CDN) http://sitespeed.io  value [10]
> > Skipping ycookiefree :Use cookie-free domains http://sitespeed.io/documentation  value [100]
> > Skipping avoidscalingimages :Never scale images in HTML http://sitespeed.io/documentation  value [0]
> > Skipping longexpirehead :Have expires headers equals or longer than one year http://sitespeed.io/documentation  value [100]
> > Skipping ycdn :Use a Content Delivery Network (CDN) http://sitespeed.io/documentation  value [0]
> > We got 70 passing tests, 0 failing 8 skipped tests
> > ------------------------------------------------- Finished checking budget
## Done, without errors.

I noticed it because I am currently implementing an option to show only the failed tests (rules) during the Budget Checking (To have a clear overview in the console output). So if I pass a parameter like _showFailedOnly_ it is also undefined during the budget checking.

**Comment by soulgalore** [comment]
I think I've missed adding to the docs that it is a Grunt config property, set it like this:
<code>grunt.config.set('includePassed', true);</code>

Best
Peter

**Comment by zenderol** [comment]
Thanks, it worked!

**Comment by soulgalore** [comment]
updated the docs
