### ISSUE TITLE
requestHeaders not working

### ISSUE THREAD

**Issue by patrickschaper** [sitespeedio/grunt-sitespeedio#8]
When using the grunt wrapper to send headers the following error occurs:

```
Running "sitespeedio:default" (sitespeedio) task
info: OS: 'win32 6.1.7601', Node.js: 'v0.12.0', sitespeed.io: '3.2.5', PhantomJS: '1.9.8', java: '1.8.0_40', browsertime: '0.9.3'
info: Will crawl from start point http://www.example.com with crawl depth 1
Fatal error: Object.keys called on non-object
```

When using sitespeed.js directly it also works fine.
`node node_modules\grunt-sitespeedio\node_modules\sitespeed.io\bin\sitespeed.js -u http://www.example.com --requestHeaders headers.json`

**Reproduction**

create a package.json with `npm init`
install grunt-sitespeedio doing `npm install grunt-sitespeedio --save-dev`

Gruntfile.js:

``` javascript
module.exports = function(grunt) {
    // load grunt modules
    grunt.loadNpmTasks('grunt-sitespeedio');

    // Project configuration.
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sitespeedio: {
            default: {
                options: {
                    url: 'http://www.example.com',
                    requestHeaders: 'headers.json' // when removed it works fine
                }
            }
        }
    });

    // Default task(s).
    grunt.registerTask('default', ['sitespeedio']);
};
```

headers.json

``` json
{
    "someKey": "someValue"
}
```

**Comment by soulgalore** [comment]
Hi @yesman82 
ah sorry my fault, there are missing documentation. In the grunt plugin, files that are JSON are instead just JSON (I updated the docs now for request headers) so in your Gruntfile you can configure the headers like:

<pre>
...
requestHeaders: {'headerName1':'value','headerName2':'value'},
...
</pre> 

Best
Peter
